# Generated by Django 5.2.11 on 2026-02-03 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='halls.cinemahall'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'row_number', 'seat_number')},
        ),
    ]
